### ISSUE TITLE
Why not helping a more popular project with the same purpose?

### ISSUE THREAD

**Issue by micnic** [nas5w/javascript-patterns#87]
Hi, found your repo on reddit and the first thought was "why creating another project that implements algorithms in JavaScript?", there is a quite popular repo already that does the same: https://github.com/trekhleb/javascript-algorithms

I am not here to criticize, but in my opinion you are wasting a lot of effort and time instead of doing something really useful for the JavaScript community. My advice is to try to contribute to the repo that I mentioned above, maybe improve their code and examples with something that you know works better.

**Comment by nas5w** [comment]
Unfortunately that project is not under active development :(

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nas5w** [comment]
It hasn’t been updated in over 4 months. I tried contributing a while back and my requests went unnoticed. Surely there’s room for another related repository, especially for people to practice this kind of theoretical work versus creating a redundant tool to be used in production. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by micnic** [comment]
In this case I think a fork would be a better solution that starting from the beginning, also would be nice to contact the original author to ask why the project is inactive and check if you can take over the the ownership, it would be a waste to lose such a popular project.

**Comment by nas5w** [comment]
To me this is like suggesting people shouldn’t write their own blog posts on topics that other people have already blogged about. I contend there is tremendous educational value in doing something yourself even if it already exists.

**Comment by rehman-00001** [comment]
Thats a topic to debate about. On one side there's no restriction to recreate things that are already existing. Thats how things evolve into better products. By recreating and by adding more stuffs that the former was lacking.

But on the other side, this whole re-inventing concept contradicts with the reason for having open-source. Invite more people to collaborate and create one sustainable product rather than having hundreds of tiny products with the similar intention. 

As @micnic pointed out, fork would have been better if the only intention is to have single repository for all algorithms & patterns! Either ways, this is just my personal opinion and would continue my contribution!

**Comment by micnic** [comment]
After 5 years, this repo seems to be dead, but the one mentioned above is still alive, the irony. Closing this issue.
